
version: '3.9'
services:
  db:
    container_name: flaskinni_db_1
    image: "postgres:latest"
    restart: always
    volumes:
      - db_storage:/var/lib/postgresql/data
    networks:
      - db_nw
    environment:
      POSTGRES_USER: postgres # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: postgres # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: flaskinni_db # The PostgreSQL default database (automatically created at first launch)
    ports:
      - '5432:5432'
    
  
  flaskapp:
    container_name: flaskinni_app_1
    build: .
    restart: always
    volumes:
      - /Users/adileettad/Projects/flaskinni:/app/flaskinni
    env_file:
      - .env
    networks:
      - db_nw
    depends_on:
      - db
    ports:
      - "80:80"
    

networks:
  db_nw:
    driver: bridge
volumes:
  db_storage:
