
version: '3.9'
services:
  db:
    image: "postgres:latest"
    restart: always
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    networks:
      - db_nw
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    container_name: flaskinni_db_1
  
  flaskapp:
    build: .
    volumes:
      - /Users/adileettad/Projects/flaskinni:/app/flaskinni
    env_file:
      - .env
    networks:
      - db_nw
    depends_on:
      - db
    ports:
      - "80:80"
    container_name: flaskinni_app_1

networks:
  db_nw:
    driver: bridge
volumes:
  dbdata:
